services:
    obs-studio:
        container_name: obs-studio
        build: 
            context: .
            dockerfile: Dockerfile
        devices:
            - /dev/dri
            - /dev/video2
        volumes:
            - /tmp/obs:/config
        environment:
            - DRINODE=/dev/dri/renderD128
            - DRI_NODE=/dev/dri/renderD128
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        ports:
            - 3001:3000
            - 3002:3001
        group_add:
            - video
        restart: unless-stopped
